development:
  adapter: redis
  url:  <%= ENV["REDIS_URL"] %>
  password: <%= ENV["REDIS_PWD"] %>

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV["REDIS_URL"] %>
  password: <%= ENV["REDIS_PWD"] %>
  channel_prefix: xmeme_production
