verbose: true
concurrency: 3
pidfile: ./tmp/pids/sidekiq.pid
logfile: ./log/sidekiq.log
queues:
  - default
  - low
production:
  concurrency: 2
development:
  concurrency: 5
staging:
  concurrency: 2