verbose: true
concurrency: 10
pidfile: ./tmp/pids/sidekiq.pid
logfile: ./log/sidekiq.log
queues:
  - default
  - low
production:
  concurrency: 25
development:
  concurrency: 15
staging:
  concurrency: 15